# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guid', models.CharField(db_index=True, max_length=50, null=True, unique=True)),
                ('classification', models.CharField(blank=True, max_length=30)),
                ('name', models.CharField(max_length=100, null=True)),
                ('sex', models.IntegerField(choices=[(1, 'Female'), (0, 'Male')])),
                ('birthday', models.DateTimeField()),
                ('degree', models.CharField(max_length=1)),
                ('title', models.CharField(max_length=1)),
                ('graduateschool', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=50)),
                ('introduction', models.TextField(blank=True)),
                ('achievement', models.TextField(blank=True)),
                ('affiliation', models.TextField(blank=True)),
                ('nationality', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('homepage', models.TextField()),
                ('photourl', models.TextField()),
                ('lastmodified', models.DateTimeField()),
                ('keywords', models.TextField()),
                ('position', models.CharField(max_length=50)),
            ],
        ),
    ]
