# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='birthday',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='graduateschool',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='lastmodified',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='nationality',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='position',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='subject',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
