# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0002_auto_20171117_1123'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='rank',
            field=models.IntegerField(null=True),
        ),
    ]
