# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0003_scholar_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='achievement',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='affiliation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='classification',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='degree',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='email',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='homepage',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='introduction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='keywords',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='photourl',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='sex',
            field=models.IntegerField(choices=[(1, 'Female'), (0, 'Male')], null=True),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='title',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
