# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-23 09:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scholar', '0004_auto_20171117_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholar.Scholar')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('members', models.ManyToManyField(through='scholar.Label', to='scholar.Scholar')),
            ],
        ),
        migrations.AddField(
            model_name='label',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scholar.Tag'),
        ),
        migrations.AddField(
            model_name='label',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
