# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0006_tag_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], null=True),
        ),
    ]
