# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0007_auto_20171127_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='graduateschool',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='subject',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
