# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0008_auto_20171130_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='sex',
            field=models.IntegerField(choices=[(1, 'Female'), (0, 'Male')], null=True),
        ),
    ]
