# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0009_auto_20171130_1208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scholar',
            name='guid',
            field=models.CharField(db_index=True, max_length=50, null=True),
        ),
    ]
