# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-08 08:19
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0011_auto_20171201_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='focus',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='scholar',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], null=True),
        ),
    ]
