# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 06:59
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholar', '0012_auto_20171208_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='scholar',
            name='statistics',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=None, null=True),
        ),
    ]
