# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 06:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scholar', '0014_auto_20171222_0553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='我的人才库', max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='scholar',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Male'), (1, 'Female')], null=True),
        ),
        migrations.AddField(
            model_name='collection',
            name='scholar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scholar.Scholar'),
        ),
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
